<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["vehicule/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["vehicule/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Idvoiture</th>
            <th>Annee</th>
            <th>Marque</th>
            <th>Modele</th>
            <th>NombreDeRoues</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $vehicule): ?>
            <tr>
                <td><?php echo $vehicule->idvoiture ?></td>
            <td><?php echo $vehicule->annee ?></td>
            <td><?php echo $vehicule->marque ?></td>
            <td><?php echo $vehicule->modele ?></td>
            <td><?php echo $vehicule->nombreDeRoues ?></td>

                <td><?php echo $this->tag->linkTo(["vehicule/edit/" . $vehicule->idvoiture, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["vehicule/delete/" . $vehicule->idvoiture, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("vehicule/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("vehicule/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("vehicule/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("vehicule/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
