-- MySQL Script generated by MySQL Workbench
-- Fri May  3 15:04:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rallyLegend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rallyLegend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rallyLegend` DEFAULT CHARACTER SET utf8 ;
USE `rallyLegend` ;

-- -----------------------------------------------------
-- Table `rallyLegend`.`chatter_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`chatter_categories` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `order` INT(11) NOT NULL DEFAULT '1',
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `color` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_name_unique` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `avatar` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'users/default.png',
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `settings` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `admin` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `users_role_id_foreign` (`role_id` ASC),
  CONSTRAINT `users_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `rallyLegend`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`chatter_discussion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`chatter_discussion` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chatter_category_id` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `sticky` TINYINT(1) NOT NULL DEFAULT '0',
  `views` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `answered` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `color` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT '#232629',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `last_reply_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `chatter_discussion_slug_unique` (`slug` ASC),
  INDEX `chatter_discussion_chatter_category_id_foreign` (`chatter_category_id` ASC),
  INDEX `chatter_discussion_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `chatter_discussion_chatter_category_id_foreign`
    FOREIGN KEY (`chatter_category_id`)
    REFERENCES `rallyLegend`.`chatter_categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chatter_discussion_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `rallyLegend`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`chatter_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`chatter_post` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `chatter_discussion_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `body` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `markdown` TINYINT(1) NOT NULL DEFAULT '0',
  `locked` TINYINT(1) NOT NULL DEFAULT '0',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `chatter_post_chatter_discussion_id_foreign` (`chatter_discussion_id` ASC),
  INDEX `chatter_post_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `chatter_post_chatter_discussion_id_foreign`
    FOREIGN KEY (`chatter_discussion_id`)
    REFERENCES `rallyLegend`.`chatter_discussion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chatter_post_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `rallyLegend`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`chatter_user_discussion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`chatter_user_discussion` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `discussion_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `discussion_id`),
  INDEX `chatter_user_discussion_user_id_index` (`user_id` ASC),
  INDEX `chatter_user_discussion_discussion_id_index` (`discussion_id` ASC),
  CONSTRAINT `chatter_user_discussion_discussion_id_foreign`
    FOREIGN KEY (`discussion_id`)
    REFERENCES `rallyLegend`.`chatter_discussion` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `chatter_user_discussion_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `rallyLegend`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`poste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`poste` (
  `idposte` INT(11) NOT NULL,
  `id_utilisateur` INT(11) NULL DEFAULT NULL,
  `id_vehicule` INT(11) NULL DEFAULT NULL,
  `descriptif` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idposte`),
  INDEX `id_utilisateur_idx` (`id_utilisateur` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rallyLegend`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`utilisateur` (
  `idutilisateur` INT(11) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `statut` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `pseudo` VARCHAR(45) NULL DEFAULT NULL,
  `signature` VARCHAR(45) NULL DEFAULT NULL,
  `motDePasse` VARCHAR(45) NULL DEFAULT NULL,
  `photo` VARCHAR(45) NULL DEFAULT NULL,
  `id_voiture` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idutilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rallyLegend`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`commentaire` (
  `idcommentaire` INT(11) NOT NULL,
  `id_post` INT(11) NULL DEFAULT NULL,
  `id_utilisateur` INT(11) NULL DEFAULT NULL,
  `commentaire` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcommentaire`),
  INDEX `idutilisateur_idx` (`id_utilisateur` ASC),
  INDEX `id_post_idx` (`id_post` ASC),
  CONSTRAINT `id_post`
    FOREIGN KEY (`id_post`)
    REFERENCES `rallyLegend`.`poste` (`idposte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `rallyLegend`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rallyLegend`.`data_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`data_types` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name_singular` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name_plural` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `icon` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `model_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `policy_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `controller` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `generate_permissions` TINYINT(1) NOT NULL DEFAULT '0',
  `server_side` TINYINT(4) NOT NULL DEFAULT '0',
  `details` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `data_types_name_unique` (`name` ASC),
  UNIQUE INDEX `data_types_slug_unique` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`data_rows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`data_rows` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_type_id` INT(10) UNSIGNED NOT NULL,
  `field` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `required` TINYINT(1) NOT NULL DEFAULT '0',
  `browse` TINYINT(1) NOT NULL DEFAULT '1',
  `read` TINYINT(1) NOT NULL DEFAULT '1',
  `edit` TINYINT(1) NOT NULL DEFAULT '1',
  `add` TINYINT(1) NOT NULL DEFAULT '1',
  `delete` TINYINT(1) NOT NULL DEFAULT '1',
  `details` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `order` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `data_rows_data_type_id_foreign` (`data_type_id` ASC),
  CONSTRAINT `data_rows_data_type_id_foreign`
    FOREIGN KEY (`data_type_id`)
    REFERENCES `rallyLegend`.`data_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`evenement` (
  `idevenement` INT(11) NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `place` INT(11) NULL DEFAULT NULL,
  `restriction` INT(11) NULL DEFAULT NULL,
  `descriptif` VARCHAR(45) NULL DEFAULT NULL,
  `titre` VARCHAR(45) NULL DEFAULT NULL,
  `lieu` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idevenement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rallyLegend`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`menus` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_name_unique` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`menu_items` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menu_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `target` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '_self',
  `icon_class` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `color` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `order` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `route` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `parameters` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `menu_items_menu_id_foreign` (`menu_id` ASC),
  CONSTRAINT `menu_items_menu_id_foreign`
    FOREIGN KEY (`menu_id`)
    REFERENCES `rallyLegend`.`menus` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`permissions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `table_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `permissions_key_index` (`key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`permission_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`permission_role` (
  `permission_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `permission_role_permission_id_index` (`permission_id` ASC),
  INDEX `permission_role_role_id_index` (`role_id` ASC),
  CONSTRAINT `permission_role_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `rallyLegend`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `rallyLegend`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`vehicule` (
  `idvoiture` INT(11) NOT NULL,
  `annee` DATETIME NULL DEFAULT NULL,
  `marque` VARCHAR(45) NULL DEFAULT NULL,
  `modele` VARCHAR(45) NULL DEFAULT NULL,
  `nombreDeRoues` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idvoiture`),
  CONSTRAINT `id_voiture`
    FOREIGN KEY (`idvoiture`)
    REFERENCES `rallyLegend`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rallyLegend`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`photo` (
  `idphoto` INT(11) NOT NULL,
  `id_utilisateur` INT(11) NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `lieu` VARCHAR(45) NULL DEFAULT NULL,
  `id_voiture` INT(11) NULL DEFAULT NULL,
  `id_evenement` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pilote` INT(11) NULL DEFAULT NULL,
  `path` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idphoto`),
  INDEX `idutilisateur_idx` (`id_utilisateur` ASC),
  INDEX `idvoiture_idx` (`id_voiture` ASC),
  INDEX `pilote_idx` (`id_pilote` ASC),
  INDEX `idevenement_idx` (`id_evenement` ASC),
  CONSTRAINT `idevenement`
    FOREIGN KEY (`id_evenement`)
    REFERENCES `rallyLegend`.`evenement` (`idevenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idutilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `rallyLegend`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idvoiture`
    FOREIGN KEY (`id_voiture`)
    REFERENCES `rallyLegend`.`vehicule` (`idvoiture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pilote`
    FOREIGN KEY (`id_pilote`)
    REFERENCES `rallyLegend`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rallyLegend`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`posts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `titre` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `contenu` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`tags` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `tag` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tag_url` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tags_tag_unique` (`tag` ASC),
  UNIQUE INDEX `tags_tag_url_unique` (`tag_url` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`post_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`post_tag` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_id` INT(10) UNSIGNED NOT NULL,
  `tag_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `post_tag_post_id_foreign` (`post_id` ASC),
  INDEX `post_tag_tag_id_foreign` (`tag_id` ASC),
  CONSTRAINT `post_tag_post_id_foreign`
    FOREIGN KEY (`post_id`)
    REFERENCES `rallyLegend`.`posts` (`id`),
  CONSTRAINT `post_tag_tag_id_foreign`
    FOREIGN KEY (`tag_id`)
    REFERENCES `rallyLegend`.`tags` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`settings` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `value` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `details` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `order` INT(11) NOT NULL DEFAULT '1',
  `group` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `settings_key_unique` (`key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`translations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`translations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `column_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `foreign_key` INT(10) UNSIGNED NOT NULL,
  `locale` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `value` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `translations_table_name_column_name_foreign_key_locale_unique` (`table_name` ASC, `column_name` ASC, `foreign_key` ASC, `locale` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rallyLegend`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rallyLegend`.`user_roles` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `user_roles_user_id_index` (`user_id` ASC),
  INDEX `user_roles_role_id_index` (`role_id` ASC),
  CONSTRAINT `user_roles_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `rallyLegend`.`roles` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_roles_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `rallyLegend`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
