<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search photo
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["photo/new", "Create photo"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "photo/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdphoto" class="col-sm-2 control-label">Idphoto</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idphoto", "type" => "number", "class" => "form-control", "id" => "fieldIdphoto"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdUtilisateur" class="col-sm-2 control-label">Id Of Utilisateur</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_utilisateur", "type" => "number", "class" => "form-control", "id" => "fieldIdUtilisateur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDate" class="col-sm-2 control-label">Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLieu" class="col-sm-2 control-label">Lieu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lieu", "size" => 30, "class" => "form-control", "id" => "fieldLieu"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdVoiture" class="col-sm-2 control-label">Id Of Voiture</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_voiture", "type" => "number", "class" => "form-control", "id" => "fieldIdVoiture"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdEvenement" class="col-sm-2 control-label">Id Of Evenement</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_evenement", "type" => "number", "class" => "form-control", "id" => "fieldIdEvenement"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdPilote" class="col-sm-2 control-label">Id Of Pilote</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pilote", "type" => "number", "class" => "form-control", "id" => "fieldIdPilote"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
