<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["photo/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["photo/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Idphoto</th>
            <th>Id Of Utilisateur</th>
            <th>Date</th>
            <th>Lieu</th>
            <th>Id Of Voiture</th>
            <th>Id Of Evenement</th>
            <th>Id Of Pilote</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $photo): ?>
            <tr>
                <td><?php echo $photo->idphoto ?></td>
            <td><?php echo $photo->id_utilisateur ?></td>
            <td><?php echo $photo->date ?></td>
            <td><?php echo $photo->lieu ?></td>
            <td><?php echo $photo->id_voiture ?></td>
            <td><?php echo $photo->id_evenement ?></td>
            <td><?php echo $photo->id_pilote ?></td>

                <td><?php echo $this->tag->linkTo(["photo/edit/" . $photo->idphoto, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["photo/delete/" . $photo->idphoto, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("photo/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("photo/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("photo/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("photo/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
