<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["utilisateur/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["utilisateur/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Idutilisateur</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Statut</th>
            <th>Mail</th>
            <th>Pseudo</th>
            <th>Signature</th>
            <th>MotDePasse</th>
            <th>Photo</th>
            <th>Id Of Voiture</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $utilisateur): ?>
            <tr>
                <td><?php echo $utilisateur->idutilisateur ?></td>
            <td><?php echo $utilisateur->nom ?></td>
            <td><?php echo $utilisateur->prenom ?></td>
            <td><?php echo $utilisateur->statut ?></td>
            <td><?php echo $utilisateur->mail ?></td>
            <td><?php echo $utilisateur->pseudo ?></td>
            <td><?php echo $utilisateur->signature ?></td>
            <td><?php echo $utilisateur->motDePasse ?></td>
            <td><?php echo $utilisateur->photo ?></td>
            <td><?php echo $utilisateur->id_voiture ?></td>

                <td><?php echo $this->tag->linkTo(["utilisateur/edit/" . $utilisateur->idutilisateur, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["utilisateur/delete/" . $utilisateur->idutilisateur, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("utilisateur/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("utilisateur/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("utilisateur/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("utilisateur/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
