<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["commentaire", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create commentaire
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "commentaire/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdcommentaire" class="col-sm-2 control-label">Idcommentaire</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idcommentaire", "type" => "number", "class" => "form-control", "id" => "fieldIdcommentaire"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdPost" class="col-sm-2 control-label">Id Of Post</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_post", "type" => "number", "class" => "form-control", "id" => "fieldIdPost"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdUtilisateur" class="col-sm-2 control-label">Id Of Utilisateur</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_utilisateur", "type" => "number", "class" => "form-control", "id" => "fieldIdUtilisateur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCommentaire" class="col-sm-2 control-label">Commentaire</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["commentaire", "size" => 30, "class" => "form-control", "id" => "fieldCommentaire"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
